# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('last_edit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
